[2025-02-10T09:39:43.457+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T09:39:43.467+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment_rollback.wait_for_tests_to_run manual__2025-02-10T09:39:08.243353+00:00 [queued]>
[2025-02-10T09:39:43.471+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment_rollback.wait_for_tests_to_run manual__2025-02-10T09:39:08.243353+00:00 [queued]>
[2025-02-10T09:39:43.472+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-10T09:39:43.478+0000] {taskinstance.py:2889} INFO - Executing <Task(ExternalTaskSensor): wait_for_tests_to_run> on 2025-02-10 09:39:08.243353+00:00
[2025-02-10T09:39:43.485+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=14955) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T09:39:43.487+0000] {standard_task_runner.py:72} INFO - Started process 14956 to run task
[2025-02-10T09:39:43.488+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment_rollback', 'wait_for_tests_to_run', 'manual__2025-02-10T09:39:08.243353+00:00', '--job-id', '576', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment_rollback.py', '--cfg-path', '/tmp/tmpjgp310mv']
[2025-02-10T09:39:43.489+0000] {standard_task_runner.py:105} INFO - Job 576: Subtask wait_for_tests_to_run
[2025-02-10T09:39:43.520+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment_rollback.wait_for_tests_to_run manual__2025-02-10T09:39:08.243353+00:00 [running]> on host fbc98e9fe6bb
[2025-02-10T09:39:43.567+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment_rollback' AIRFLOW_CTX_TASK_ID='wait_for_tests_to_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T09:39:08.243353+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T09:39:08.243353+00:00'
[2025-02-10T09:39:43.569+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-10T09:39:43.569+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-10T09:39:43.569+0000] {logging_mixin.py:190} INFO - Current task name:wait_for_tests_to_run state:running start_date:2025-02-10 09:39:43.467759+00:00
[2025-02-10T09:39:43.569+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_rollback and current dag run status:running
[2025-02-10T09:39:43.570+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T09:39:43.570+0000] {baseoperator.py:421} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2025-02-10T09:39:43.584+0000] {external_task.py:258} INFO - Poking for tasks ['tests_finished'] in dag run_e2e_tests on 2025-02-10T09:39:09.243353+00:00 ... 
[2025-02-10T09:39:43.585+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/session.py:97: DeprecationWarning: This method is deprecated and will be removed in future.
  return func(*args, session=session, **kwargs)

[2025-02-10T09:39:43.602+0000] {taskinstance.py:309} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-02-10T09:39:43.602+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T09:39:43.623+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-10T09:39:43.640+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-10T09:39:43.642+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-10T09:40:15.799+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T09:40:15.809+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment_rollback.wait_for_tests_to_run manual__2025-02-10T09:39:08.243353+00:00 [queued]>
[2025-02-10T09:40:15.814+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment_rollback.wait_for_tests_to_run manual__2025-02-10T09:39:08.243353+00:00 [queued]>
[2025-02-10T09:40:15.814+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-10T09:40:15.820+0000] {taskinstance.py:2889} INFO - Executing <Task(ExternalTaskSensor): wait_for_tests_to_run> on 2025-02-10 09:39:08.243353+00:00
[2025-02-10T09:40:15.825+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=14968) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T09:40:15.827+0000] {standard_task_runner.py:72} INFO - Started process 14969 to run task
[2025-02-10T09:40:15.827+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment_rollback', 'wait_for_tests_to_run', 'manual__2025-02-10T09:39:08.243353+00:00', '--job-id', '577', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment_rollback.py', '--cfg-path', '/tmp/tmpt1omw9br']
[2025-02-10T09:40:15.828+0000] {standard_task_runner.py:105} INFO - Job 577: Subtask wait_for_tests_to_run
[2025-02-10T09:40:15.869+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment_rollback.wait_for_tests_to_run manual__2025-02-10T09:39:08.243353+00:00 [running]> on host fbc98e9fe6bb
[2025-02-10T09:40:15.922+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment_rollback' AIRFLOW_CTX_TASK_ID='wait_for_tests_to_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T09:39:08.243353+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T09:39:08.243353+00:00'
[2025-02-10T09:40:15.923+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-10T09:40:15.923+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-10T09:40:15.924+0000] {logging_mixin.py:190} INFO - Current task name:wait_for_tests_to_run state:running start_date:2025-02-10 09:40:15.810207+00:00
[2025-02-10T09:40:15.924+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_rollback and current dag run status:running
[2025-02-10T09:40:15.924+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T09:40:15.925+0000] {baseoperator.py:421} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2025-02-10T09:40:15.939+0000] {external_task.py:258} INFO - Poking for tasks ['tests_finished'] in dag run_e2e_tests on 2025-02-10T09:39:09.243353+00:00 ... 
[2025-02-10T09:40:15.939+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/session.py:97: DeprecationWarning: This method is deprecated and will be removed in future.
  return func(*args, session=session, **kwargs)

[2025-02-10T09:40:15.955+0000] {taskinstance.py:309} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-02-10T09:40:15.956+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T09:40:15.962+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-10T09:40:15.982+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-10T09:40:15.985+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-10T09:40:48.013+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T09:40:48.023+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment_rollback.wait_for_tests_to_run manual__2025-02-10T09:39:08.243353+00:00 [queued]>
[2025-02-10T09:40:48.027+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment_rollback.wait_for_tests_to_run manual__2025-02-10T09:39:08.243353+00:00 [queued]>
[2025-02-10T09:40:48.028+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-10T09:40:48.034+0000] {taskinstance.py:2889} INFO - Executing <Task(ExternalTaskSensor): wait_for_tests_to_run> on 2025-02-10 09:39:08.243353+00:00
[2025-02-10T09:40:48.040+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=14981) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T09:40:48.041+0000] {standard_task_runner.py:72} INFO - Started process 14982 to run task
[2025-02-10T09:40:48.044+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment_rollback', 'wait_for_tests_to_run', 'manual__2025-02-10T09:39:08.243353+00:00', '--job-id', '578', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment_rollback.py', '--cfg-path', '/tmp/tmpa9ndtxlm']
[2025-02-10T09:40:48.045+0000] {standard_task_runner.py:105} INFO - Job 578: Subtask wait_for_tests_to_run
[2025-02-10T09:40:48.084+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment_rollback.wait_for_tests_to_run manual__2025-02-10T09:39:08.243353+00:00 [running]> on host fbc98e9fe6bb
[2025-02-10T09:40:48.131+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment_rollback' AIRFLOW_CTX_TASK_ID='wait_for_tests_to_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T09:39:08.243353+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T09:39:08.243353+00:00'
[2025-02-10T09:40:48.132+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-10T09:40:48.132+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-10T09:40:48.132+0000] {logging_mixin.py:190} INFO - Current task name:wait_for_tests_to_run state:running start_date:2025-02-10 09:40:48.023438+00:00
[2025-02-10T09:40:48.133+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_rollback and current dag run status:running
[2025-02-10T09:40:48.133+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T09:40:48.133+0000] {baseoperator.py:421} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2025-02-10T09:40:48.146+0000] {external_task.py:258} INFO - Poking for tasks ['tests_finished'] in dag run_e2e_tests on 2025-02-10T09:39:09.243353+00:00 ... 
[2025-02-10T09:40:48.147+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/session.py:97: DeprecationWarning: This method is deprecated and will be removed in future.
  return func(*args, session=session, **kwargs)

[2025-02-10T09:40:48.152+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 64.612633 seconds exceeds the specified timeout of 60.0.
[2025-02-10T09:40:48.160+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-10T09:40:48.161+0000] {logging_mixin.py:190} INFO - Task start:2025-02-10 09:40:48.023438+00:00 end:2025-02-10 09:40:48.160575+00:00 duration:0.137137
[2025-02-10T09:40:48.161+0000] {logging_mixin.py:190} INFO - Task:<Task(ExternalTaskSensor): wait_for_tests_to_run> dag:<DAG: cluster_deployment_rollback> dagrun:<DagRun cluster_deployment_rollback @ 2025-02-10 09:39:08.243353+00:00: manual__2025-02-10T09:39:08.243353+00:00, state:running, queued_at: 2025-02-10 09:39:08.258989+00:00. externally triggered: True>
[2025-02-10T09:40:48.161+0000] {logging_mixin.py:190} INFO - Failure caused by Sensor has timed out; run duration of 64.612633 seconds exceeds the specified timeout of 60.0.
[2025-02-10T09:40:48.162+0000] {taskinstance.py:1225} INFO - Immediate failure requested. Marking task as FAILED. dag_id=cluster_deployment_rollback, task_id=wait_for_tests_to_run, run_id=manual__2025-02-10T09:39:08.243353+00:00, execution_date=20250210T093908, start_date=20250210T094048, end_date=20250210T094048
[2025-02-10T09:40:48.162+0000] {taskinstance.py:1563} INFO - Executing callback at index 0: rollback_all_previous_tasks
[2025-02-10T09:40:48.165+0000] {logging_mixin.py:190} INFO - Start rollback on pre-deployment...
[2025-02-10T09:40:58.168+0000] {logging_mixin.py:190} INFO - Rollback on pre-deployment completed successfully...
[2025-02-10T09:40:58.172+0000] {logging_mixin.py:190} INFO - Start rollback on pre-check...
[2025-02-10T09:41:08.175+0000] {logging_mixin.py:190} INFO - Rollback on pre-check completed successfully...
[2025-02-10T09:41:08.178+0000] {logging_mixin.py:190} INFO - Start rollback on download stack...
[2025-02-10T09:41:18.181+0000] {logging_mixin.py:190} INFO - Rollback on download stack completed successfully...
[2025-02-10T09:41:18.219+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T09:41:18.220+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 578 for task wait_for_tests_to_run (Sensor has timed out; run duration of 64.612633 seconds exceeds the specified timeout of 60.0.; 14982)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 64.612633 seconds exceeds the specified timeout of 60.0.
[2025-02-10T09:41:18.279+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-10T09:41:18.326+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-10T09:41:18.331+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
