[2025-02-10T12:44:55.963+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T12:44:56.016+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment_rollback.wait_for_tests_to_run manual__2025-02-10T12:43:22.617398+00:00 [queued]>
[2025-02-10T12:44:56.080+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment_rollback.wait_for_tests_to_run manual__2025-02-10T12:43:22.617398+00:00 [queued]>
[2025-02-10T12:44:56.080+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-10T12:44:56.146+0000] {taskinstance.py:2889} INFO - Executing <Task(ExternalTaskSensor): wait_for_tests_to_run> on 2025-02-10 12:43:22.617398+00:00
[2025-02-10T12:44:56.184+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=297) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T12:44:56.187+0000] {standard_task_runner.py:72} INFO - Started process 300 to run task
[2025-02-10T12:44:56.198+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment_rollback', 'wait_for_tests_to_run', 'manual__2025-02-10T12:43:22.617398+00:00', '--job-id', '592', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment_rollback.py', '--cfg-path', '/tmp/tmpbu4w48g0']
[2025-02-10T12:44:56.203+0000] {standard_task_runner.py:105} INFO - Job 592: Subtask wait_for_tests_to_run
[2025-02-10T12:44:56.343+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment_rollback.wait_for_tests_to_run manual__2025-02-10T12:43:22.617398+00:00 [running]> on host 1999c8c59930
[2025-02-10T12:44:56.628+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment_rollback' AIRFLOW_CTX_TASK_ID='wait_for_tests_to_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T12:43:22.617398+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T12:43:22.617398+00:00'
[2025-02-10T12:44:56.633+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-10T12:44:56.643+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-10T12:44:56.644+0000] {logging_mixin.py:190} INFO - Current task name:wait_for_tests_to_run state:running start_date:2025-02-10 12:44:56.024473+00:00
[2025-02-10T12:44:56.644+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_rollback and current dag run status:running
[2025-02-10T12:44:56.646+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T12:44:56.647+0000] {baseoperator.py:421} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2025-02-10T12:44:56.749+0000] {external_task.py:258} INFO - Poking for tasks ['tests_finished'] in dag run_e2e_tests on 2025-02-10T12:43:23.617398+00:00 ... 
[2025-02-10T12:44:56.750+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/session.py:97: DeprecationWarning: This method is deprecated and will be removed in future.
  return func(*args, session=session, **kwargs)

[2025-02-10T12:44:56.821+0000] {taskinstance.py:309} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-02-10T12:44:56.822+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T12:44:56.861+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-10T12:44:56.905+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-10T12:45:29.666+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T12:45:29.690+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment_rollback.wait_for_tests_to_run manual__2025-02-10T12:43:22.617398+00:00 [queued]>
[2025-02-10T12:45:29.702+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment_rollback.wait_for_tests_to_run manual__2025-02-10T12:43:22.617398+00:00 [queued]>
[2025-02-10T12:45:29.704+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-10T12:45:29.718+0000] {taskinstance.py:2889} INFO - Executing <Task(ExternalTaskSensor): wait_for_tests_to_run> on 2025-02-10 12:43:22.617398+00:00
[2025-02-10T12:45:29.744+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=380) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T12:45:29.746+0000] {standard_task_runner.py:72} INFO - Started process 395 to run task
[2025-02-10T12:45:29.758+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment_rollback', 'wait_for_tests_to_run', 'manual__2025-02-10T12:43:22.617398+00:00', '--job-id', '599', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment_rollback.py', '--cfg-path', '/tmp/tmpcp69w04c']
[2025-02-10T12:45:29.760+0000] {standard_task_runner.py:105} INFO - Job 599: Subtask wait_for_tests_to_run
[2025-02-10T12:45:29.857+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment_rollback.wait_for_tests_to_run manual__2025-02-10T12:43:22.617398+00:00 [running]> on host 1999c8c59930
[2025-02-10T12:45:29.921+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment_rollback' AIRFLOW_CTX_TASK_ID='wait_for_tests_to_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T12:43:22.617398+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T12:43:22.617398+00:00'
[2025-02-10T12:45:29.922+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-10T12:45:29.922+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-10T12:45:29.922+0000] {logging_mixin.py:190} INFO - Current task name:wait_for_tests_to_run state:running start_date:2025-02-10 12:45:29.691021+00:00
[2025-02-10T12:45:29.922+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_rollback and current dag run status:running
[2025-02-10T12:45:29.922+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T12:45:29.923+0000] {baseoperator.py:421} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2025-02-10T12:45:29.951+0000] {external_task.py:258} INFO - Poking for tasks ['tests_finished'] in dag run_e2e_tests on 2025-02-10T12:43:23.617398+00:00 ... 
[2025-02-10T12:45:29.952+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/session.py:97: DeprecationWarning: This method is deprecated and will be removed in future.
  return func(*args, session=session, **kwargs)

[2025-02-10T12:45:29.997+0000] {taskinstance.py:309} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2025-02-10T12:45:29.998+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T12:45:30.010+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-10T12:45:30.054+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-10T12:45:30.055+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-10T12:46:02.034+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T12:46:02.065+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment_rollback.wait_for_tests_to_run manual__2025-02-10T12:43:22.617398+00:00 [queued]>
[2025-02-10T12:46:02.075+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment_rollback.wait_for_tests_to_run manual__2025-02-10T12:43:22.617398+00:00 [queued]>
[2025-02-10T12:46:02.075+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-10T12:46:02.087+0000] {taskinstance.py:2889} INFO - Executing <Task(ExternalTaskSensor): wait_for_tests_to_run> on 2025-02-10 12:43:22.617398+00:00
[2025-02-10T12:46:02.093+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=427) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T12:46:02.094+0000] {standard_task_runner.py:72} INFO - Started process 428 to run task
[2025-02-10T12:46:02.099+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment_rollback', 'wait_for_tests_to_run', 'manual__2025-02-10T12:43:22.617398+00:00', '--job-id', '605', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment_rollback.py', '--cfg-path', '/tmp/tmpg7hn7rc9']
[2025-02-10T12:46:02.102+0000] {standard_task_runner.py:105} INFO - Job 605: Subtask wait_for_tests_to_run
[2025-02-10T12:46:02.154+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment_rollback.wait_for_tests_to_run manual__2025-02-10T12:43:22.617398+00:00 [running]> on host 1999c8c59930
[2025-02-10T12:46:02.209+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment_rollback' AIRFLOW_CTX_TASK_ID='wait_for_tests_to_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T12:43:22.617398+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T12:43:22.617398+00:00'
[2025-02-10T12:46:02.210+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-10T12:46:02.211+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-10T12:46:02.211+0000] {logging_mixin.py:190} INFO - Current task name:wait_for_tests_to_run state:running start_date:2025-02-10 12:46:02.066914+00:00
[2025-02-10T12:46:02.211+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_rollback and current dag run status:running
[2025-02-10T12:46:02.211+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T12:46:02.212+0000] {baseoperator.py:421} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2025-02-10T12:46:02.226+0000] {external_task.py:258} INFO - Poking for tasks ['tests_finished'] in dag run_e2e_tests on 2025-02-10T12:43:23.617398+00:00 ... 
[2025-02-10T12:46:02.227+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/session.py:97: DeprecationWarning: This method is deprecated and will be removed in future.
  return func(*args, session=session, **kwargs)

[2025-02-10T12:46:02.233+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 65.786987 seconds exceeds the specified timeout of 60.0.
[2025-02-10T12:46:02.241+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-10T12:46:02.241+0000] {logging_mixin.py:190} INFO - Task start:2025-02-10 12:46:02.066914+00:00 end:2025-02-10 12:46:02.240865+00:00 duration:0.173951
[2025-02-10T12:46:02.241+0000] {logging_mixin.py:190} INFO - Task:<Task(ExternalTaskSensor): wait_for_tests_to_run> dag:<DAG: cluster_deployment_rollback> dagrun:<DagRun cluster_deployment_rollback @ 2025-02-10 12:43:22.617398+00:00: manual__2025-02-10T12:43:22.617398+00:00, state:running, queued_at: 2025-02-10 12:43:22.660263+00:00. externally triggered: True>
[2025-02-10T12:46:02.242+0000] {logging_mixin.py:190} INFO - Failure caused by Sensor has timed out; run duration of 65.786987 seconds exceeds the specified timeout of 60.0.
[2025-02-10T12:46:02.242+0000] {taskinstance.py:1225} INFO - Immediate failure requested. Marking task as FAILED. dag_id=cluster_deployment_rollback, task_id=wait_for_tests_to_run, run_id=manual__2025-02-10T12:43:22.617398+00:00, execution_date=20250210T124322, start_date=20250210T124602, end_date=20250210T124602
[2025-02-10T12:46:02.243+0000] {taskinstance.py:1563} INFO - Executing callback at index 0: rollback_all_previous_tasks
[2025-02-10T12:46:02.247+0000] {logging_mixin.py:190} INFO - Start rollback on pre-deployment...
[2025-02-10T12:46:12.261+0000] {logging_mixin.py:190} INFO - Rollback on pre-deployment completed successfully...
[2025-02-10T12:46:12.287+0000] {logging_mixin.py:190} INFO - Start rollback on download stack...
[2025-02-10T12:46:22.290+0000] {logging_mixin.py:190} INFO - Rollback on download stack completed successfully...
[2025-02-10T12:46:22.294+0000] {logging_mixin.py:190} INFO - Start rollback on pre-check...
[2025-02-10T12:46:32.299+0000] {logging_mixin.py:190} INFO - Rollback on pre-check completed successfully...
[2025-02-10T12:46:32.380+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T12:46:32.394+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 605 for task wait_for_tests_to_run (Sensor has timed out; run duration of 65.786987 seconds exceeds the specified timeout of 60.0.; 428)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 65.786987 seconds exceeds the specified timeout of 60.0.
[2025-02-10T12:46:32.465+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-10T12:46:32.526+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
