[2025-02-06T13:28:41.161+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-06T13:28:41.170+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_2nd_scenario.read_from_xcom manual__2025-02-06T13:28:34.565462+00:00 [queued]>
[2025-02-06T13:28:41.174+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_2nd_scenario.read_from_xcom manual__2025-02-06T13:28:34.565462+00:00 [queued]>
[2025-02-06T13:28:41.174+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-06T13:28:41.181+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): read_from_xcom> on 2025-02-06 13:28:34.565462+00:00
[2025-02-06T13:28:41.188+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2848) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-06T13:28:41.190+0000] {standard_task_runner.py:72} INFO - Started process 2849 to run task
[2025-02-06T13:28:41.190+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'demo_2nd_scenario', 'read_from_xcom', 'manual__2025-02-06T13:28:34.565462+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/demo_2nd_scenario.py', '--cfg-path', '/tmp/tmpe496ee1t']
[2025-02-06T13:28:41.191+0000] {standard_task_runner.py:105} INFO - Job 35: Subtask read_from_xcom
[2025-02-06T13:28:41.224+0000] {task_command.py:467} INFO - Running <TaskInstance: demo_2nd_scenario.read_from_xcom manual__2025-02-06T13:28:34.565462+00:00 [running]> on host ***-worker-1
[2025-02-06T13:28:41.267+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='demo_2nd_scenario' AIRFLOW_CTX_TASK_ID='read_from_xcom' AIRFLOW_CTX_EXECUTION_DATE='2025-02-06T13:28:34.565462+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-06T13:28:34.565462+00:00'
[2025-02-06T13:28:41.268+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-06T13:28:41.268+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-06T13:28:41.268+0000] {logging_mixin.py:190} INFO - Current task name:read_from_xcom state:running start_date:2025-02-06 13:28:41.170793+00:00
[2025-02-06T13:28:41.269+0000] {logging_mixin.py:190} INFO - Dag name:demo_2nd_scenario and current dag run status:running
[2025-02-06T13:28:41.269+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-06T13:28:41.269+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: read_from_xcom_fn() missing 1 required positional argument: 'xcom_data'
[2025-02-06T13:28:41.287+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-06T13:28:41.287+0000] {logging_mixin.py:190} INFO - Task start:2025-02-06 13:28:41.170793+00:00 end:2025-02-06 13:28:41.286756+00:00 duration:0.115963
[2025-02-06T13:28:41.288+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): read_from_xcom> dag:<DAG: demo_2nd_scenario> dagrun:<DagRun demo_2nd_scenario @ 2025-02-06 13:28:34.565462+00:00: manual__2025-02-06T13:28:34.565462+00:00, state:running, queued_at: 2025-02-06 13:28:34.593291+00:00. externally triggered: True>
[2025-02-06T13:28:41.288+0000] {logging_mixin.py:190} INFO - Failure caused by read_from_xcom_fn() missing 1 required positional argument: 'xcom_data'
[2025-02-06T13:28:41.289+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=demo_2nd_scenario, task_id=read_from_xcom, run_id=manual__2025-02-06T13:28:34.565462+00:00, execution_date=20250206T132834, start_date=20250206T132841, end_date=20250206T132841
[2025-02-06T13:28:41.300+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-06T13:28:41.300+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 35 for task read_from_xcom (read_from_xcom_fn() missing 1 required positional argument: 'xcom_data'; 2849)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: read_from_xcom_fn() missing 1 required positional argument: 'xcom_data'
[2025-02-06T13:28:41.324+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-06T13:28:41.339+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-06T13:28:41.341+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
