[2025-02-10T12:43:26.573+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T12:43:26.585+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment_rollback.pre_deployment_checks manual__2025-02-10T12:43:22.617398+00:00 [queued]>
[2025-02-10T12:43:26.590+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment_rollback.pre_deployment_checks manual__2025-02-10T12:43:22.617398+00:00 [queued]>
[2025-02-10T12:43:26.591+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-10T12:43:26.600+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): pre_deployment_checks> on 2025-02-10 12:43:22.617398+00:00
[2025-02-10T12:43:26.622+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=123) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T12:43:26.624+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment_rollback', 'pre_deployment_checks', 'manual__2025-02-10T12:43:22.617398+00:00', '--job-id', '579', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment_rollback.py', '--cfg-path', '/tmp/tmpb8iy0vq9']
[2025-02-10T12:43:26.631+0000] {standard_task_runner.py:72} INFO - Started process 124 to run task
[2025-02-10T12:43:26.632+0000] {standard_task_runner.py:105} INFO - Job 579: Subtask pre_deployment_checks
[2025-02-10T12:43:26.723+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment_rollback.pre_deployment_checks manual__2025-02-10T12:43:22.617398+00:00 [running]> on host 1999c8c59930
[2025-02-10T12:43:26.795+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment_rollback' AIRFLOW_CTX_TASK_ID='pre_deployment_checks' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T12:43:22.617398+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T12:43:22.617398+00:00'
[2025-02-10T12:43:26.797+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-10T12:43:26.797+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-10T12:43:26.797+0000] {logging_mixin.py:190} INFO - Current task name:pre_deployment_checks state:running start_date:2025-02-10 12:43:26.585765+00:00
[2025-02-10T12:43:26.797+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_rollback and current dag run status:running
[2025-02-10T12:43:26.798+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T12:43:26.798+0000] {baseoperator.py:421} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-02-10T12:43:26.799+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venv53yvrdcj --system-site-packages --python=python
[2025-02-10T12:43:26.801+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T12:43:28.213+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.8.final.0-64 in 710ms
[2025-02-10T12:43:28.219+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venv53yvrdcj, clear=False, no_vcs_ignore=False, global=True)
[2025-02-10T12:43:28.219+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-02-10T12:43:28.221+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-02-10T12:43:28.222+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-02-10T12:43:28.246+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venv53yvrdcj/bin/pip install -r /tmp/venv53yvrdcj/requirements.txt
[2025-02-10T12:43:28.263+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T12:43:31.174+0000] {process_utils.py:194} INFO - Requirement already satisfied: pandas==2.1.4 in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venv53yvrdcj/requirements.txt (line 1)) (2.1.4)
[2025-02-10T12:43:31.198+0000] {process_utils.py:194} INFO - Requirement already satisfied: numpy<2,>=1.26.0 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv53yvrdcj/requirements.txt (line 1)) (1.26.4)
[2025-02-10T12:43:31.218+0000] {process_utils.py:194} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv53yvrdcj/requirements.txt (line 1)) (2.9.0.post0)
[2025-02-10T12:43:31.223+0000] {process_utils.py:194} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv53yvrdcj/requirements.txt (line 1)) (2024.2)
[2025-02-10T12:43:31.224+0000] {process_utils.py:194} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv53yvrdcj/requirements.txt (line 1)) (2024.2)
[2025-02-10T12:43:31.225+0000] {process_utils.py:194} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.1.4->-r /tmp/venv53yvrdcj/requirements.txt (line 1)) (1.17.0)
[2025-02-10T12:43:32.282+0000] {process_utils.py:194} INFO - 
[2025-02-10T12:43:32.283+0000] {process_utils.py:194} INFO - [notice] A new release of pip is available: 24.3.1 -> 25.0.1
[2025-02-10T12:43:32.283+0000] {process_utils.py:194} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-02-10T12:43:32.527+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venv53yvrdcj/bin/python /tmp/venv-callrhfc9q29/script.py /tmp/venv-callrhfc9q29/script.in /tmp/venv-callrhfc9q29/script.out /tmp/venv-callrhfc9q29/string_args.txt /tmp/venv-callrhfc9q29/termination.log
[2025-02-10T12:43:32.538+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T12:43:50.754+0000] {process_utils.py:194} INFO - [2025-02-10T12:43:50.701+0000] {script.py:23} INFO - Starting pre-deployment checks...
[2025-02-10T12:43:50.832+0000] {process_utils.py:194} INFO - [2025-02-10T12:43:50.791+0000] {script.py:38} INFO - Pre-deployment checks completed
[2025-02-10T12:43:55.918+0000] {python.py:240} INFO - Done. Returned value was: {'services_status': {'running': 4}, 'deployment_ready': True, 'timestamp': '2025-02-10T12:43:50.791360'}
[2025-02-10T12:43:56.156+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T12:43:56.160+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cluster_deployment_rollback, task_id=pre_deployment_checks, run_id=manual__2025-02-10T12:43:22.617398+00:00, execution_date=20250210T124322, start_date=20250210T124326, end_date=20250210T124356
[2025-02-10T12:43:56.273+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-10T12:43:56.278+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-10T12:43:56.279+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_rollback queued_at:2025-02-10 12:43:22.660263+00:00
[2025-02-10T12:43:56.280+0000] {logging_mixin.py:190} INFO - Task hostname:1999c8c59930 operator:PythonVirtualenvOperator
[2025-02-10T12:43:56.406+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-10T12:43:56.627+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-10T12:43:56.628+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
