[2025-02-10T12:44:17.289+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T12:44:17.465+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment_rollback.download_stack manual__2025-02-10T12:43:30.486106+00:00 [queued]>
[2025-02-10T12:44:17.533+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment_rollback.download_stack manual__2025-02-10T12:43:30.486106+00:00 [queued]>
[2025-02-10T12:44:17.534+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-10T12:44:17.603+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): download_stack> on 2025-02-10 12:43:30.486106+00:00
[2025-02-10T12:44:17.648+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=212) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T12:44:17.651+0000] {standard_task_runner.py:72} INFO - Started process 251 to run task
[2025-02-10T12:44:17.658+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment_rollback', 'download_stack', 'manual__2025-02-10T12:43:30.486106+00:00', '--job-id', '588', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment_rollback.py', '--cfg-path', '/tmp/tmpfl6rm1dw']
[2025-02-10T12:44:17.674+0000] {standard_task_runner.py:105} INFO - Job 588: Subtask download_stack
[2025-02-10T12:44:17.865+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment_rollback.download_stack manual__2025-02-10T12:43:30.486106+00:00 [running]> on host 1999c8c59930
[2025-02-10T12:44:18.065+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment_rollback' AIRFLOW_CTX_TASK_ID='download_stack' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T12:43:30.486106+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T12:43:30.486106+00:00'
[2025-02-10T12:44:18.068+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-10T12:44:18.093+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-10T12:44:18.094+0000] {logging_mixin.py:190} INFO - Current task name:download_stack state:running start_date:2025-02-10 12:44:17.470120+00:00
[2025-02-10T12:44:18.094+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_rollback and current dag run status:running
[2025-02-10T12:44:18.095+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T12:44:18.096+0000] {baseoperator.py:421} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-02-10T12:44:18.097+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvzm8v358w --system-site-packages --python=python
[2025-02-10T12:44:18.103+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T12:44:20.973+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.8.final.0-64 in 1072ms
[2025-02-10T12:44:20.986+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venvzm8v358w, clear=False, no_vcs_ignore=False, global=True)
[2025-02-10T12:44:20.996+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-02-10T12:44:20.997+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-02-10T12:44:21.023+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-02-10T12:44:21.398+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvzm8v358w/bin/pip install -r /tmp/venvzm8v358w/requirements.txt
[2025-02-10T12:44:21.413+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T12:44:26.045+0000] {process_utils.py:194} INFO - Requirement already satisfied: pandas==2.1.4 in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venvzm8v358w/requirements.txt (line 1)) (2.1.4)
[2025-02-10T12:44:26.113+0000] {process_utils.py:194} INFO - Requirement already satisfied: numpy<2,>=1.26.0 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvzm8v358w/requirements.txt (line 1)) (1.26.4)
[2025-02-10T12:44:26.138+0000] {process_utils.py:194} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvzm8v358w/requirements.txt (line 1)) (2.9.0.post0)
[2025-02-10T12:44:26.140+0000] {process_utils.py:194} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvzm8v358w/requirements.txt (line 1)) (2024.2)
[2025-02-10T12:44:26.143+0000] {process_utils.py:194} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvzm8v358w/requirements.txt (line 1)) (2024.2)
[2025-02-10T12:44:26.154+0000] {process_utils.py:194} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.1.4->-r /tmp/venvzm8v358w/requirements.txt (line 1)) (1.17.0)
[2025-02-10T12:44:27.784+0000] {process_utils.py:194} INFO - 
[2025-02-10T12:44:27.864+0000] {process_utils.py:194} INFO - [notice] A new release of pip is available: 24.3.1 -> 25.0.1
[2025-02-10T12:44:27.867+0000] {process_utils.py:194} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-02-10T12:44:30.068+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvzm8v358w/bin/python /tmp/venv-callwx6g0u70/script.py /tmp/venv-callwx6g0u70/script.in /tmp/venv-callwx6g0u70/script.out /tmp/venv-callwx6g0u70/string_args.txt /tmp/venv-callwx6g0u70/termination.log
[2025-02-10T12:44:30.089+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T12:44:36.065+0000] {process_utils.py:194} INFO - [2025-02-10T12:44:36.062+0000] {script.py:30} INFO - Starting download stack...
[2025-02-10T12:44:46.157+0000] {process_utils.py:194} INFO - [2025-02-10T12:44:46.136+0000] {script.py:46} INFO - Writing download report to to: /opt/***/data/download_report_from_v1.0.0.json
[2025-02-10T12:44:46.170+0000] {process_utils.py:194} INFO - [2025-02-10T12:44:46.169+0000] {script.py:50} INFO - Download stack completed:
[2025-02-10T12:44:46.171+0000] {process_utils.py:194} INFO - Total size: 1200.0MB
[2025-02-10T12:44:46.172+0000] {process_utils.py:194} INFO - Total time: 240s
[2025-02-10T12:44:46.172+0000] {process_utils.py:194} INFO - Download speed: 5.0MB/s
[2025-02-10T12:44:52.446+0000] {python.py:240} INFO - Done. Returned value was: {'stacks': ['baseos', 'gi'], 'total_size_mb': 1200.0, 'total_time_seconds': 240, 'download_speed_mbs': 5.0, 'status': 'success', 'details': [{'stack': 'baseos', 'size_mb': 1000, 'status': 'completed', 'time': 180}, {'stack': 'gi', 'size_mb': 200, 'status': 'completed', 'time': 60}], 'timestamp': '2025-02-10T12:44:46.135560'}
[2025-02-10T12:44:52.636+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T12:44:52.642+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cluster_deployment_rollback, task_id=download_stack, run_id=manual__2025-02-10T12:43:30.486106+00:00, execution_date=20250210T124330, start_date=20250210T124417, end_date=20250210T124452
[2025-02-10T12:44:52.666+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-10T12:44:52.668+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-10T12:44:52.668+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_rollback queued_at:2025-02-10 12:43:30.515748+00:00
[2025-02-10T12:44:52.669+0000] {logging_mixin.py:190} INFO - Task hostname:1999c8c59930 operator:PythonVirtualenvOperator
[2025-02-10T12:44:52.751+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-10T12:44:52.770+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-02-10T12:44:52.824+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
