[2025-02-07T09:25:28.365+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T09:25:28.403+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment.pre_deployment_checks manual__2025-02-07T09:25:25.684317+00:00 [queued]>
[2025-02-07T09:25:28.416+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment.pre_deployment_checks manual__2025-02-07T09:25:25.684317+00:00 [queued]>
[2025-02-07T09:25:28.417+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-07T09:25:28.433+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): pre_deployment_checks> on 2025-02-07 09:25:25.684317+00:00
[2025-02-07T09:25:28.443+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=7575) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-07T09:25:28.444+0000] {standard_task_runner.py:72} INFO - Started process 7576 to run task
[2025-02-07T09:25:28.447+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment', 'pre_deployment_checks', 'manual__2025-02-07T09:25:25.684317+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment.py', '--cfg-path', '/tmp/tmp246k6auw']
[2025-02-07T09:25:28.449+0000] {standard_task_runner.py:105} INFO - Job 131: Subtask pre_deployment_checks
[2025-02-07T09:25:28.501+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment.pre_deployment_checks manual__2025-02-07T09:25:25.684317+00:00 [running]> on host ***-worker
[2025-02-07T09:25:28.576+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment' AIRFLOW_CTX_TASK_ID='pre_deployment_checks' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T09:25:25.684317+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-07T09:25:25.684317+00:00'
[2025-02-07T09:25:28.578+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-07T09:25:28.578+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-07T09:25:28.578+0000] {logging_mixin.py:190} INFO - Current task name:pre_deployment_checks state:running start_date:2025-02-07 09:25:28.405707+00:00
[2025-02-07T09:25:28.579+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment and current dag run status:running
[2025-02-07T09:25:28.579+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T09:25:28.580+0000] {baseoperator.py:421} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-02-07T09:25:28.581+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvw_nhqb8i --system-site-packages --python=python
[2025-02-07T09:25:28.583+0000] {process_utils.py:190} INFO - Output:
[2025-02-07T09:25:29.140+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.8.final.0-64 in 170ms
[2025-02-07T09:25:29.141+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venvw_nhqb8i, clear=False, no_vcs_ignore=False, global=True)
[2025-02-07T09:25:29.142+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-02-07T09:25:29.143+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-02-07T09:25:29.143+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-02-07T09:25:29.163+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvw_nhqb8i/bin/pip install -r /tmp/venvw_nhqb8i/requirements.txt
[2025-02-07T09:25:29.165+0000] {process_utils.py:190} INFO - Output:
[2025-02-07T09:25:30.203+0000] {process_utils.py:194} INFO - Requirement already satisfied: pandas==2.1.4 in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venvw_nhqb8i/requirements.txt (line 1)) (2.1.4)
[2025-02-07T09:25:30.207+0000] {process_utils.py:194} INFO - Requirement already satisfied: numpy<2,>=1.26.0 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvw_nhqb8i/requirements.txt (line 1)) (1.26.4)
[2025-02-07T09:25:30.208+0000] {process_utils.py:194} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvw_nhqb8i/requirements.txt (line 1)) (2.9.0.post0)
[2025-02-07T09:25:30.208+0000] {process_utils.py:194} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvw_nhqb8i/requirements.txt (line 1)) (2024.2)
[2025-02-07T09:25:30.209+0000] {process_utils.py:194} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvw_nhqb8i/requirements.txt (line 1)) (2024.2)
[2025-02-07T09:25:30.211+0000] {process_utils.py:194} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.1.4->-r /tmp/venvw_nhqb8i/requirements.txt (line 1)) (1.17.0)
[2025-02-07T09:25:30.711+0000] {process_utils.py:194} INFO - 
[2025-02-07T09:25:30.715+0000] {process_utils.py:194} INFO - [notice] A new release of pip is available: 24.3.1 -> 25.0
[2025-02-07T09:25:30.716+0000] {process_utils.py:194} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-02-07T09:25:30.835+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvw_nhqb8i/bin/python /tmp/venv-calln3pf7m9q/script.py /tmp/venv-calln3pf7m9q/script.in /tmp/venv-calln3pf7m9q/script.out /tmp/venv-calln3pf7m9q/string_args.txt /tmp/venv-calln3pf7m9q/termination.log
[2025-02-07T09:25:30.837+0000] {process_utils.py:190} INFO - Output:
[2025-02-07T09:25:32.844+0000] {process_utils.py:194} INFO - [2025-02-07T09:25:32.844+0000] {script.py:23} INFO - Starting pre-deployment checks...
[2025-02-07T09:25:32.847+0000] {process_utils.py:194} INFO - [2025-02-07T09:25:32.847+0000] {script.py:38} INFO - Pre-deployment checks completed
[2025-02-07T09:25:33.361+0000] {python.py:240} INFO - Done. Returned value was: {'services_status': {'running': 4}, 'deployment_ready': True, 'timestamp': '2025-02-07T09:25:32.847605'}
[2025-02-07T09:25:33.498+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-07T09:25:33.500+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cluster_deployment, task_id=pre_deployment_checks, run_id=manual__2025-02-07T09:25:25.684317+00:00, execution_date=20250207T092525, start_date=20250207T092528, end_date=20250207T092533
[2025-02-07T09:25:33.537+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-07T09:25:33.537+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-07T09:25:33.537+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment queued_at:2025-02-07 09:25:25.702413+00:00
[2025-02-07T09:25:33.538+0000] {logging_mixin.py:190} INFO - Task hostname:***-worker operator:PythonVirtualenvOperator
[2025-02-07T09:25:33.587+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-07T09:25:33.615+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
