[2025-02-10T12:43:29.924+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T12:43:29.973+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment_rollback.pre_deployment_checks manual__2025-02-10T12:43:24.873249+00:00 [queued]>
[2025-02-10T12:43:29.988+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment_rollback.pre_deployment_checks manual__2025-02-10T12:43:24.873249+00:00 [queued]>
[2025-02-10T12:43:29.989+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-10T12:43:30.015+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): pre_deployment_checks> on 2025-02-10 12:43:24.873249+00:00
[2025-02-10T12:43:30.034+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=18043) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T12:43:30.044+0000] {standard_task_runner.py:72} INFO - Started process 18047 to run task
[2025-02-10T12:43:30.056+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment_rollback', 'pre_deployment_checks', 'manual__2025-02-10T12:43:24.873249+00:00', '--job-id', '580', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment_rollback.py', '--cfg-path', '/tmp/tmpptkvi0nn']
[2025-02-10T12:43:30.057+0000] {standard_task_runner.py:105} INFO - Job 580: Subtask pre_deployment_checks
[2025-02-10T12:43:30.274+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment_rollback.pre_deployment_checks manual__2025-02-10T12:43:24.873249+00:00 [running]> on host fbc98e9fe6bb
[2025-02-10T12:43:30.486+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment_rollback' AIRFLOW_CTX_TASK_ID='pre_deployment_checks' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T12:43:24.873249+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T12:43:24.873249+00:00'
[2025-02-10T12:43:30.500+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-10T12:43:30.501+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-10T12:43:30.504+0000] {logging_mixin.py:190} INFO - Current task name:pre_deployment_checks state:running start_date:2025-02-10 12:43:29.983123+00:00
[2025-02-10T12:43:30.504+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_rollback and current dag run status:running
[2025-02-10T12:43:30.505+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T12:43:30.505+0000] {baseoperator.py:421} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-02-10T12:43:30.511+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvevbrh4jl --system-site-packages --python=python
[2025-02-10T12:43:30.524+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T12:43:32.312+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.8.final.0-64 in 683ms
[2025-02-10T12:43:32.332+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venvevbrh4jl, clear=False, no_vcs_ignore=False, global=True)
[2025-02-10T12:43:32.333+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-02-10T12:43:32.349+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-02-10T12:43:32.350+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-02-10T12:43:32.400+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvevbrh4jl/bin/pip install -r /tmp/venvevbrh4jl/requirements.txt
[2025-02-10T12:43:32.403+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T12:43:38.434+0000] {process_utils.py:194} INFO - Requirement already satisfied: pandas==2.1.4 in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venvevbrh4jl/requirements.txt (line 1)) (2.1.4)
[2025-02-10T12:43:38.501+0000] {process_utils.py:194} INFO - Requirement already satisfied: numpy<2,>=1.26.0 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvevbrh4jl/requirements.txt (line 1)) (1.26.4)
[2025-02-10T12:43:38.504+0000] {process_utils.py:194} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvevbrh4jl/requirements.txt (line 1)) (2.9.0.post0)
[2025-02-10T12:43:38.507+0000] {process_utils.py:194} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvevbrh4jl/requirements.txt (line 1)) (2024.2)
[2025-02-10T12:43:38.509+0000] {process_utils.py:194} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvevbrh4jl/requirements.txt (line 1)) (2024.2)
[2025-02-10T12:43:38.533+0000] {process_utils.py:194} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.1.4->-r /tmp/venvevbrh4jl/requirements.txt (line 1)) (1.17.0)
[2025-02-10T12:43:40.856+0000] {process_utils.py:194} INFO - 
[2025-02-10T12:43:40.859+0000] {process_utils.py:194} INFO - [notice] A new release of pip is available: 24.3.1 -> 25.0.1
[2025-02-10T12:43:40.860+0000] {process_utils.py:194} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-02-10T12:43:41.289+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvevbrh4jl/bin/python /tmp/venv-callrbzdgzj2/script.py /tmp/venv-callrbzdgzj2/script.in /tmp/venv-callrbzdgzj2/script.out /tmp/venv-callrbzdgzj2/string_args.txt /tmp/venv-callrbzdgzj2/termination.log
[2025-02-10T12:43:41.329+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T12:43:57.796+0000] {process_utils.py:194} INFO - [2025-02-10T12:43:57.758+0000] {script.py:23} INFO - Starting pre-deployment checks...
[2025-02-10T12:43:57.868+0000] {process_utils.py:194} INFO - [2025-02-10T12:43:57.867+0000] {script.py:38} INFO - Pre-deployment checks completed
[2025-02-10T12:44:00.000+0000] {python.py:240} INFO - Done. Returned value was: {'services_status': {'running': 4}, 'deployment_ready': True, 'timestamp': '2025-02-10T12:43:57.867198'}
[2025-02-10T12:44:00.187+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T12:44:00.192+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cluster_deployment_rollback, task_id=pre_deployment_checks, run_id=manual__2025-02-10T12:43:24.873249+00:00, execution_date=20250210T124324, start_date=20250210T124329, end_date=20250210T124400
[2025-02-10T12:44:00.246+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-10T12:44:00.247+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-10T12:44:00.247+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_rollback queued_at:2025-02-10 12:43:24.927822+00:00
[2025-02-10T12:44:00.247+0000] {logging_mixin.py:190} INFO - Task hostname:fbc98e9fe6bb operator:PythonVirtualenvOperator
[2025-02-10T12:44:00.335+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-10T12:44:00.486+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-10T12:44:00.494+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
