[2025-02-11T09:12:16.966+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T09:12:16.979+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_workflow.failing_task manual__2025-02-11T11:11:45+02:00 [queued]>
[2025-02-11T09:12:16.986+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_workflow.failing_task manual__2025-02-11T11:11:45+02:00 [queued]>
[2025-02-11T09:12:16.986+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-11T09:12:17.003+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): failing_task> on 2025-02-11 09:11:45+00:00
[2025-02-11T09:12:17.011+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=15201) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-11T09:12:17.012+0000] {standard_task_runner.py:72} INFO - Started process 15204 to run task
[2025-02-11T09:12:17.022+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'api_workflow', 'failing_task', 'manual__2025-02-11T11:11:45+02:00', '--job-id', '644', '--raw', '--subdir', 'DAGS_FOLDER/generate_dags_from_yaml.py', '--cfg-path', '/tmp/tmpxfuvmlqv']
[2025-02-11T09:12:17.023+0000] {standard_task_runner.py:105} INFO - Job 644: Subtask failing_task
[2025-02-11T09:12:17.085+0000] {task_command.py:467} INFO - Running <TaskInstance: api_workflow.failing_task manual__2025-02-11T11:11:45+02:00 [running]> on host 1999c8c59930
[2025-02-11T09:12:17.156+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_workflow' AIRFLOW_CTX_TASK_ID='failing_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T09:11:45+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T11:11:45+02:00'
[2025-02-11T09:12:17.160+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-11T09:12:17.161+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-11T09:12:17.162+0000] {logging_mixin.py:190} INFO - Current task name:failing_task state:running start_date:2025-02-11 09:12:16.979843+00:00
[2025-02-11T09:12:17.162+0000] {logging_mixin.py:190} INFO - Dag name:api_workflow and current dag run status:running
[2025-02-11T09:12:17.163+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-11T09:12:17.164+0000] {api_tasks_for_ymls.py:85} INFO - Starting failing task...
[2025-02-11T09:12:22.168+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_tasks/api_tasks_for_ymls.py", line 87, in failing_task_fn
    raise SimulatedFailure(
api_tasks_for_ymls.SimulatedFailure: Task execution timeout (Code: TIMEOUT_001, Severity: FATAL)
[2025-02-11T09:12:22.194+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-11T09:12:22.195+0000] {logging_mixin.py:190} INFO - Task start:2025-02-11 09:12:16.979843+00:00 end:2025-02-11 09:12:22.193492+00:00 duration:5.213649
[2025-02-11T09:12:22.195+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): failing_task> dag:<DAG: api_workflow> dagrun:<DagRun api_workflow @ 2025-02-11 09:11:45+00:00: manual__2025-02-11T11:11:45+02:00, state:running, queued_at: 2025-02-11 09:12:08.472241+00:00. externally triggered: True>
[2025-02-11T09:12:22.195+0000] {logging_mixin.py:190} INFO - Failure caused by Task execution timeout (Code: TIMEOUT_001, Severity: FATAL)
[2025-02-11T09:12:22.196+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=api_workflow, task_id=failing_task, run_id=manual__2025-02-11T11:11:45+02:00, execution_date=20250211T091145, start_date=20250211T091216, end_date=20250211T091222
[2025-02-11T09:12:22.213+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-11T09:12:22.215+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 644 for task failing_task (Task execution timeout (Code: TIMEOUT_001, Severity: FATAL); 15204)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_tasks/api_tasks_for_ymls.py", line 87, in failing_task_fn
    raise SimulatedFailure(
api_tasks_for_ymls.SimulatedFailure: Task execution timeout (Code: TIMEOUT_001, Severity: FATAL)
[2025-02-11T09:12:22.265+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-11T09:12:22.290+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-11T09:12:22.291+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
