[2025-02-07T14:19:30.353+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T14:19:30.363+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment.download_stack manual__2025-02-07T14:19:14.887679+00:00 [queued]>
[2025-02-07T14:19:30.367+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment.download_stack manual__2025-02-07T14:19:14.887679+00:00 [queued]>
[2025-02-07T14:19:30.367+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-07T14:19:30.374+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): download_stack> on 2025-02-07 14:19:14.887679+00:00
[2025-02-07T14:19:30.380+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=104) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-07T14:19:30.381+0000] {standard_task_runner.py:72} INFO - Started process 105 to run task
[2025-02-07T14:19:30.383+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment', 'download_stack', 'manual__2025-02-07T14:19:14.887679+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment.py', '--cfg-path', '/tmp/tmpawpuemzb']
[2025-02-07T14:19:30.384+0000] {standard_task_runner.py:105} INFO - Job 90: Subtask download_stack
[2025-02-07T14:19:30.419+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment.download_stack manual__2025-02-07T14:19:14.887679+00:00 [running]> on host 35f5723d0861
[2025-02-07T14:19:30.466+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment' AIRFLOW_CTX_TASK_ID='download_stack' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T14:19:14.887679+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-07T14:19:14.887679+00:00'
[2025-02-07T14:19:30.467+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-07T14:19:30.467+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-07T14:19:30.468+0000] {logging_mixin.py:190} INFO - Current task name:download_stack state:running start_date:2025-02-07 14:19:30.363502+00:00
[2025-02-07T14:19:30.468+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment and current dag run status:running
[2025-02-07T14:19:30.468+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T14:19:30.468+0000] {baseoperator.py:421} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-02-07T14:19:30.469+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvo0wtf0n5 --system-site-packages --python=python
[2025-02-07T14:19:30.470+0000] {process_utils.py:190} INFO - Output:
[2025-02-07T14:19:31.287+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.8.final.0-64 in 405ms
[2025-02-07T14:19:31.289+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venvo0wtf0n5, clear=False, no_vcs_ignore=False, global=True)
[2025-02-07T14:19:31.289+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-02-07T14:19:31.290+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-02-07T14:19:31.291+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-02-07T14:19:31.308+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvo0wtf0n5/bin/pip install -r /tmp/venvo0wtf0n5/requirements.txt
[2025-02-07T14:19:31.309+0000] {process_utils.py:190} INFO - Output:
[2025-02-07T14:19:32.267+0000] {process_utils.py:194} INFO - Requirement already satisfied: pandas==2.1.4 in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venvo0wtf0n5/requirements.txt (line 1)) (2.1.4)
[2025-02-07T14:19:32.271+0000] {process_utils.py:194} INFO - Requirement already satisfied: numpy<2,>=1.26.0 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvo0wtf0n5/requirements.txt (line 1)) (1.26.4)
[2025-02-07T14:19:32.272+0000] {process_utils.py:194} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvo0wtf0n5/requirements.txt (line 1)) (2.9.0.post0)
[2025-02-07T14:19:32.272+0000] {process_utils.py:194} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvo0wtf0n5/requirements.txt (line 1)) (2024.2)
[2025-02-07T14:19:32.273+0000] {process_utils.py:194} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvo0wtf0n5/requirements.txt (line 1)) (2024.2)
[2025-02-07T14:19:32.274+0000] {process_utils.py:194} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.1.4->-r /tmp/venvo0wtf0n5/requirements.txt (line 1)) (1.17.0)
[2025-02-07T14:19:32.662+0000] {process_utils.py:194} INFO - 
[2025-02-07T14:19:32.662+0000] {process_utils.py:194} INFO - [notice] A new release of pip is available: 24.3.1 -> 25.0
[2025-02-07T14:19:32.662+0000] {process_utils.py:194} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-02-07T14:19:32.733+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvo0wtf0n5/bin/python /tmp/venv-calln71u6ebv/script.py /tmp/venv-calln71u6ebv/script.in /tmp/venv-calln71u6ebv/script.out /tmp/venv-calln71u6ebv/string_args.txt /tmp/venv-calln71u6ebv/termination.log
[2025-02-07T14:19:32.734+0000] {process_utils.py:190} INFO - Output:
[2025-02-07T14:19:35.768+0000] {process_utils.py:194} INFO - [2025-02-07T14:19:35.762+0000] {script.py:24} INFO - Starting download stack...
[2025-02-07T14:19:45.783+0000] {process_utils.py:194} INFO - [2025-02-07T14:19:45.780+0000] {script.py:40} INFO - Download stack completed:
[2025-02-07T14:19:45.801+0000] {process_utils.py:194} INFO - Total size: 1200.0MB
[2025-02-07T14:19:45.801+0000] {process_utils.py:194} INFO - Total time: 240s
[2025-02-07T14:19:45.802+0000] {process_utils.py:194} INFO - Download speed: 5.0MB/s
[2025-02-07T14:19:46.267+0000] {python.py:240} INFO - Done. Returned value was: {'stacks': ['baseos', 'gi'], 'total_size_mb': 1200.0, 'total_time_seconds': 240, 'download_speed_mbs': 5.0, 'status': 'success', 'details': [{'stack': 'baseos', 'size_mb': 1000, 'status': 'completed', 'time': 180}, {'stack': 'gi', 'size_mb': 200, 'status': 'completed', 'time': 60}], 'timestamp': '2025-02-07T14:19:45.780511'}
[2025-02-07T14:19:46.300+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-07T14:19:46.301+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cluster_deployment, task_id=download_stack, run_id=manual__2025-02-07T14:19:14.887679+00:00, execution_date=20250207T141914, start_date=20250207T141930, end_date=20250207T141946
[2025-02-07T14:19:46.309+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-07T14:19:46.310+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-07T14:19:46.310+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment queued_at:2025-02-07 14:19:14.922280+00:00
[2025-02-07T14:19:46.310+0000] {logging_mixin.py:190} INFO - Task hostname:35f5723d0861 operator:PythonVirtualenvOperator
[2025-02-07T14:19:46.350+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-07T14:19:46.373+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-07T14:19:46.374+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
