[2025-02-10T12:44:45.389+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T12:44:45.409+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment_rollback.run_pre_check manual__2025-02-10T12:43:24.873249+00:00 [queued]>
[2025-02-10T12:44:45.416+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment_rollback.run_pre_check manual__2025-02-10T12:43:24.873249+00:00 [queued]>
[2025-02-10T12:44:45.417+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-10T12:44:45.425+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): run_pre_check> on 2025-02-10 12:43:24.873249+00:00
[2025-02-10T12:44:45.435+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=18227) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T12:44:45.443+0000] {standard_task_runner.py:72} INFO - Started process 18256 to run task
[2025-02-10T12:44:45.461+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment_rollback', 'run_pre_check', 'manual__2025-02-10T12:43:24.873249+00:00', '--job-id', '591', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment_rollback.py', '--cfg-path', '/tmp/tmpqsmf_45w']
[2025-02-10T12:44:45.463+0000] {standard_task_runner.py:105} INFO - Job 591: Subtask run_pre_check
[2025-02-10T12:44:45.848+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment_rollback.run_pre_check manual__2025-02-10T12:43:24.873249+00:00 [running]> on host fbc98e9fe6bb
[2025-02-10T12:44:46.227+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment_rollback' AIRFLOW_CTX_TASK_ID='run_pre_check' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T12:43:24.873249+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T12:43:24.873249+00:00'
[2025-02-10T12:44:46.230+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-10T12:44:46.231+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-10T12:44:46.232+0000] {logging_mixin.py:190} INFO - Current task name:run_pre_check state:running start_date:2025-02-10 12:44:45.409958+00:00
[2025-02-10T12:44:46.245+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_rollback and current dag run status:running
[2025-02-10T12:44:46.246+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T12:44:46.248+0000] {baseoperator.py:421} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-02-10T12:44:46.252+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venv7jo27qh9 --system-site-packages --python=python
[2025-02-10T12:44:46.282+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T12:44:49.152+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.8.final.0-64 in 865ms
[2025-02-10T12:44:49.156+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venv7jo27qh9, clear=False, no_vcs_ignore=False, global=True)
[2025-02-10T12:44:49.157+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-02-10T12:44:49.158+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-02-10T12:44:49.158+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-02-10T12:44:49.316+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venv7jo27qh9/bin/pip install -r /tmp/venv7jo27qh9/requirements.txt
[2025-02-10T12:44:49.370+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T12:44:53.370+0000] {process_utils.py:194} INFO - Requirement already satisfied: pandas==2.1.4 in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venv7jo27qh9/requirements.txt (line 1)) (2.1.4)
[2025-02-10T12:44:53.382+0000] {process_utils.py:194} INFO - Requirement already satisfied: numpy<2,>=1.26.0 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv7jo27qh9/requirements.txt (line 1)) (1.26.4)
[2025-02-10T12:44:53.389+0000] {process_utils.py:194} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv7jo27qh9/requirements.txt (line 1)) (2.9.0.post0)
[2025-02-10T12:44:53.393+0000] {process_utils.py:194} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv7jo27qh9/requirements.txt (line 1)) (2024.2)
[2025-02-10T12:44:53.411+0000] {process_utils.py:194} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venv7jo27qh9/requirements.txt (line 1)) (2024.2)
[2025-02-10T12:44:53.413+0000] {process_utils.py:194} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.1.4->-r /tmp/venv7jo27qh9/requirements.txt (line 1)) (1.17.0)
[2025-02-10T12:44:55.249+0000] {process_utils.py:194} INFO - 
[2025-02-10T12:44:55.270+0000] {process_utils.py:194} INFO - [notice] A new release of pip is available: 24.3.1 -> 25.0.1
[2025-02-10T12:44:55.271+0000] {process_utils.py:194} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-02-10T12:44:55.929+0000] {python.py:513} INFO - Use 'pickle' as serializer.
[2025-02-10T12:44:56.018+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venv7jo27qh9/bin/python /tmp/venv-calldwcqrtrk/script.py /tmp/venv-calldwcqrtrk/script.in /tmp/venv-calldwcqrtrk/script.out /tmp/venv-calldwcqrtrk/string_args.txt /tmp/venv-calldwcqrtrk/termination.log
[2025-02-10T12:44:56.032+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T12:45:02.066+0000] {process_utils.py:194} INFO - [2025-02-10T12:45:02.052+0000] {script.py:23} INFO - Starting run pre-checks...
[2025-02-10T12:45:02.078+0000] {process_utils.py:194} INFO - [2025-02-10T12:45:02.063+0000] {script.py:26} INFO - Pre Deployment Report: {'services_status': {'running': 4}, 'deployment_ready': True, 'timestamp': '2025-02-10T12:43:57.867198'}
[2025-02-10T12:45:02.082+0000] {process_utils.py:194} INFO - [2025-02-10T12:45:02.071+0000] {script.py:41} INFO - Pre-checks completed:
[2025-02-10T12:45:02.083+0000] {process_utils.py:194} INFO - Total memory usage: 1536%
[2025-02-10T12:45:02.084+0000] {process_utils.py:194} INFO - Status: PASS
[2025-02-10T12:45:03.803+0000] {python.py:240} INFO - Done. Returned value was: {'total_memory_usage_mb': 1536, 'checks_passed': True, 'timestamp': '2025-02-10T12:45:02.071117'}
[2025-02-10T12:45:04.479+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T12:45:04.496+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cluster_deployment_rollback, task_id=run_pre_check, run_id=manual__2025-02-10T12:43:24.873249+00:00, execution_date=20250210T124324, start_date=20250210T124445, end_date=20250210T124504
[2025-02-10T12:45:04.537+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-10T12:45:04.541+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-10T12:45:04.542+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_rollback queued_at:2025-02-10 12:43:24.927822+00:00
[2025-02-10T12:45:04.543+0000] {logging_mixin.py:190} INFO - Task hostname:fbc98e9fe6bb operator:PythonVirtualenvOperator
[2025-02-10T12:45:04.668+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-10T12:45:04.837+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-10T12:45:04.844+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
