[2025-02-10T09:39:10.432+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T09:39:10.444+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cluster_deployment_rollback.pre_deployment_checks manual__2025-02-10T09:39:08.243353+00:00 [queued]>
[2025-02-10T09:39:10.449+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cluster_deployment_rollback.pre_deployment_checks manual__2025-02-10T09:39:08.243353+00:00 [queued]>
[2025-02-10T09:39:10.449+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-10T09:39:10.458+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): pre_deployment_checks> on 2025-02-10 09:39:08.243353+00:00
[2025-02-10T09:39:10.467+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=14861) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T09:39:10.471+0000] {standard_task_runner.py:72} INFO - Started process 14870 to run task
[2025-02-10T09:39:10.469+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cluster_deployment_rollback', 'pre_deployment_checks', 'manual__2025-02-10T09:39:08.243353+00:00', '--job-id', '573', '--raw', '--subdir', 'DAGS_FOLDER/cluster_deployment_rollback.py', '--cfg-path', '/tmp/tmpu5_coubc']
[2025-02-10T09:39:10.475+0000] {standard_task_runner.py:105} INFO - Job 573: Subtask pre_deployment_checks
[2025-02-10T09:39:10.544+0000] {task_command.py:467} INFO - Running <TaskInstance: cluster_deployment_rollback.pre_deployment_checks manual__2025-02-10T09:39:08.243353+00:00 [running]> on host fbc98e9fe6bb
[2025-02-10T09:39:10.640+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cluster_deployment_rollback' AIRFLOW_CTX_TASK_ID='pre_deployment_checks' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T09:39:08.243353+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T09:39:08.243353+00:00'
[2025-02-10T09:39:10.646+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-10T09:39:10.647+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-10T09:39:10.647+0000] {logging_mixin.py:190} INFO - Current task name:pre_deployment_checks state:running start_date:2025-02-10 09:39:10.444668+00:00
[2025-02-10T09:39:10.647+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_rollback and current dag run status:running
[2025-02-10T09:39:10.648+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T09:39:10.648+0000] {baseoperator.py:421} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-02-10T09:39:10.651+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvyool659c --system-site-packages --python=python
[2025-02-10T09:39:10.653+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T09:39:11.422+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.8.final.0-64 in 354ms
[2025-02-10T09:39:11.433+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venvyool659c, clear=False, no_vcs_ignore=False, global=True)
[2025-02-10T09:39:11.434+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-02-10T09:39:11.435+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2025-02-10T09:39:11.435+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-02-10T09:39:11.469+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvyool659c/bin/pip install -r /tmp/venvyool659c/requirements.txt
[2025-02-10T09:39:11.470+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T09:39:12.630+0000] {process_utils.py:194} INFO - Requirement already satisfied: pandas==2.1.4 in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venvyool659c/requirements.txt (line 1)) (2.1.4)
[2025-02-10T09:39:12.635+0000] {process_utils.py:194} INFO - Requirement already satisfied: numpy<2,>=1.26.0 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvyool659c/requirements.txt (line 1)) (1.26.4)
[2025-02-10T09:39:12.635+0000] {process_utils.py:194} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvyool659c/requirements.txt (line 1)) (2.9.0.post0)
[2025-02-10T09:39:12.636+0000] {process_utils.py:194} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvyool659c/requirements.txt (line 1)) (2024.2)
[2025-02-10T09:39:12.637+0000] {process_utils.py:194} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.12/site-packages (from pandas==2.1.4->-r /tmp/venvyool659c/requirements.txt (line 1)) (2024.2)
[2025-02-10T09:39:12.639+0000] {process_utils.py:194} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.1.4->-r /tmp/venvyool659c/requirements.txt (line 1)) (1.17.0)
[2025-02-10T09:39:13.057+0000] {process_utils.py:194} INFO - 
[2025-02-10T09:39:13.058+0000] {process_utils.py:194} INFO - [notice] A new release of pip is available: 24.3.1 -> 25.0.1
[2025-02-10T09:39:13.058+0000] {process_utils.py:194} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-02-10T09:39:13.146+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venvyool659c/bin/python /tmp/venv-call32mu35zg/script.py /tmp/venv-call32mu35zg/script.in /tmp/venv-call32mu35zg/script.out /tmp/venv-call32mu35zg/string_args.txt /tmp/venv-call32mu35zg/termination.log
[2025-02-10T09:39:13.147+0000] {process_utils.py:190} INFO - Output:
[2025-02-10T09:39:15.445+0000] {process_utils.py:194} INFO - [2025-02-10T09:39:15.443+0000] {script.py:23} INFO - Starting pre-deployment checks...
[2025-02-10T09:39:15.446+0000] {process_utils.py:194} INFO - [2025-02-10T09:39:15.446+0000] {script.py:38} INFO - Pre-deployment checks completed
[2025-02-10T09:39:15.845+0000] {python.py:240} INFO - Done. Returned value was: {'services_status': {'running': 4}, 'deployment_ready': True, 'timestamp': '2025-02-10T09:39:15.446514'}
[2025-02-10T09:39:15.876+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T09:39:15.877+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cluster_deployment_rollback, task_id=pre_deployment_checks, run_id=manual__2025-02-10T09:39:08.243353+00:00, execution_date=20250210T093908, start_date=20250210T093910, end_date=20250210T093915
[2025-02-10T09:39:15.885+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-10T09:39:15.886+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-10T09:39:15.886+0000] {logging_mixin.py:190} INFO - Dag name:cluster_deployment_rollback queued_at:2025-02-10 09:39:08.258989+00:00
[2025-02-10T09:39:15.886+0000] {logging_mixin.py:190} INFO - Task hostname:fbc98e9fe6bb operator:PythonVirtualenvOperator
[2025-02-10T09:39:15.904+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-10T09:39:15.956+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-10T09:39:15.959+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
